package ltl2rabin;

import com.google.common.collect.ImmutableSet;
import ltl2rabin.LTL.Formula;
import ltl2rabin.LTL.PropEquivalenceClass;

import java.util.HashMap;
import java.util.List;
import java.util.Set;

/**
 * A <code>SubAutomatonFromFormulaFactory</code> can create a {@link SubAutomaton} from an {@link Formula} object,
 * using its alphabet. Once constructed, every generated automaton will be put into a cache, so constructing a
 * SubAutomaton several times from the same formula will be efficient.
 */
public class SubAutomatonFromFormulaFactory extends RabinAutomatonFactory<Formula,
        List<MojmirAutomaton.State<PropEquivalenceClass, Set<String>>>,
        Set<String>> {
    private final MojmirAutomatonFactoryFromFormula mojmirAutomatonFactory;
    private final SubAutomatonFromMojmirFactory subAutomatonFromMojmirFactory;
    private static HashMap<Formula, SubAutomaton> subAutomata = new HashMap<>();

    /**
     * A <code>SubAutomatonFromFormulaFactory</code> will be usable for one alphabet.
     *
     * @param alphabet    The set of letters that will be used to construct a SubAutomaton automaton.
     */
    public SubAutomatonFromFormulaFactory(ImmutableSet<Set<String>> alphabet) {
        super(alphabet);
        mojmirAutomatonFactory = new MojmirAutomatonFactoryFromFormula(alphabet);
        subAutomatonFromMojmirFactory = new SubAutomatonFromMojmirFactory(alphabet);
    }

    /**
     * This method returns a {@link SubAutomaton} generated by the given {@link Formula}. The result is cached and
     * returned again, if the method is called again for the same Formula.
     *
     * @param psi    An arbitrary LTL formula.
     * @return       A {@link SubAutomaton} accepting the input formula.
     */
    public SubAutomaton createFrom(Formula psi) {
        SubAutomaton result = getFromCache(psi);
        if (null == result) {
            MojmirAutomaton<PropEquivalenceClass, Set<String>> ma = mojmirAutomatonFactory.createFrom(psi);
            result = subAutomatonFromMojmirFactory.createFrom(ma);
            putIntoCache(psi, result);
        }
        return result;
    }

    /**
     * Puts a constructed automaton into the cache. A {@link SubAutomaton} is identified by the formula <i>psi</i>
     *
     * @param psi             The formula the automaton accepts
     * @param subAutomaton    The {@link SubAutomaton} constructed by a factory.
     */
    protected static void putIntoCache(Formula psi, SubAutomaton subAutomaton) {
        subAutomata.put(psi, subAutomaton);
    }

    /**
     * Looks for a previously constructed automaton for psi
     *
     * @param psi The formula the automaton has been constructed from.
     * @return An automaton accepting <i>psi</i>, if it has been constructed before. Null otherwise.
     */
    protected static SubAutomaton getFromCache(Formula psi) {
        return subAutomata.get(psi);
    }
}
